### ISSUE TITLE
ZfcUserAdmin

### ISSUE THREAD

**Issue by Danielss89** [ZF-Commons/RFC#4]
Comments and discussion for: ZfcUserAdmin (https://github.com/ZF-Commons/RFC/wiki/RFC:-ZfcUserAdmin)

**Comment by ghost** [comment]
Why not just a generic ZfcCrud that could handle managing users (and any other entities)?

**Comment by Hounddog** [comment]
I think this RFC should also incorporate the authentication with overrides for admin Login.

**Comment by Danielss89** [comment]
@SpiffyJr Hmm, then what about banning and listing users.
I've been thinking about adding control for the ZfcUser config also, like: allow registration, enable captcha and all that stuff.

**Comment by ghost** [comment]
Well, listing would be the READ part of the CRUD. Good point on the banning.

**Comment by ScraperDave** [comment]
There is a re-write of ZcfUser going on to version 2.0. This could be considered part of the separate extension module options.

**Comment by Danielss89** [comment]
Yeah, do we have an ETA on zfcuser 2.0?

Mvh.
Daniel Strøm

**Comment by ScraperDave** [comment]
There seems to be some dedicated people in at least getting together some backs 2.0 package. They say "soon" but that maybe relative. You should ask the team over there. https://github.com/ZF-Commons/ZfcUser
