### ISSUE TITLE
ZfcAdmin

### ISSUE THREAD

**Issue by juriansluiman** [ZF-Commons/RFC#5]

**Comment by Thinkscape** [comment]
I don't like the idea you've drafted. It seems like a "skeleton" module ("ghost" module). It doesn't provide any functionality, the "admin layout" is not that much desired IMO, it does not provide any interfaces on which other modules could connect and "attach" to it.  

It seems like its main purpose at this point is to define an 'admin' route into which which you can attach "child_routes". Do we really need a module for that ?

IMHO an admin module should primarly focus on providing interfaces and providing a common ground for other modules to attach, collect and provide admin options/values/switches from other modules, possibly be a gateway for permission checks and displaying admin options (and modifying them). I'm ok with the module not having any UI, but in that case it has to have some purpose and serve at least those functions brought up by me above.

**Comment by weierophinney** [comment]
I actually appreciate how minimal it is. Different sites have different administration needs, as do different modules. Making this as slim as possible means that the developer can craft an admin interface to incorporate modules on an as-needed basis.

I would expect that for things like ACLs and whatnot, once we have a module in place for managing those, we'd also provide an admin for that -- and view helpers that admin interfaces can utilize to allow specifying module-specific ACLs. Overall, though, the idea of an "admin interface" is typically one of having a common screen with navigation that hides behind authentication and authorization. I think that's captured nicely in this RFC.

**Comment by juriansluiman** [comment]
Because ZfcAdmin is now accepted and part of ZF-Commons, I will close this issue now.
