### ISSUE TITLE
Layout error

### ISSUE THREAD

**Issue by shadowfax** [ZF-Commons/RFC#6]
Most of the functionality in this module is the layout, however it breaks the layout!

When in an Action controller I do:

$viewModel = new ViewModel():
$viewModel->setTerminal(true);
return $viewModel;

The admin layout still renders when it shouldn't. There is no clean way to make it stop rendering

**Comment by Hounddog** [comment]
This issue does not belong  to the rfc. Please move it to the appropriate place and close.

**Comment by akrabat** [comment]
Wrong project
